### ISSUE TITLE
Test code functions that do not work because they do not specify argument values

### ISSUE THREAD

**Issue by NEONKID** [ABMI/RadiologyFeatureExtraction#1]
```R
predictedImages <-reconDim(x = predicted, imageProcessingSettings = imageProcessingSettings)
```
The problem is that if you do not specify the value of the imageProcessingSettings argument in your test code because the argument following the x argument is a convolution, you will not be able to find it.

**Comment by chandryou** [comment]
https://github.com/ABMI/RadiologyFeatureExtraction/commit/d4fa60c6d7420ae9fb58876b06208e3138edd11c
